### ISSUE TITLE
Use terraform modules instead of hardcoded resources

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/hydroform#28]
**Description**
The actual resource definition to provision a cluster should not be part of hydroform itself. Instead, they should be provided by well-defined terraform modules written and maintained by operations experts.

**Reasons**
Don't require code changes anytime the resources for provisioning a cluster are changing.
Separation of concern, hydroform takes care of terraform integration, modules take care of provisioning a cluster on a specific provider
Decoupling, no provider specific knowledge required inside hydroform.

**Criterias**
- No provider specific terraform resources left in hydroform sources
- Provisioning is based on https://github.com/kyma-incubator/terraform-modules
- Modules are downloaded at runtime similar way as terraform providers, no hard bundling

**Comment by clebs** [comment]
Now we have the necessary functionality in Hydroform to use external modules.

Unfortunately only the azure module could be integrated because other modules either do not exist yet or have issues.
The following tasks should address the issues:
- GKE module issues and integration: #92
- Gardener module integration(probably needs to be fixed after #92): #93

**Comment by a-thaler** [comment]
Please create a first release of the modules (0.1.0) and use this as reference to avoid a release of CLI with a master ref, or use just an explicit revision hash.
